//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAMTeam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int FormId { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string UserMessage { get; set; }
        public System.DateTime MessageDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
