//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAMTeam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchesId { get; set; }
        public Nullable<int> FirstTeamId { get; set; }
        public Nullable<int> SecondTeamId { get; set; }
        public int FirstTeamScore { get; set; }
        public int SecondTeamScore { get; set; }
        public Nullable<System.DateTime> Match_date { get; set; }
        public Nullable<int> CompId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual CompetitionType CompetitionType { get; set; }
    }
}
