//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheAMTeam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int Team { get; set; }
        public int TshirtNO { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NameAlias { get; set; }
        public Nullable<int> NationalityId { get; set; }
    
        public virtual Nationality Nationality { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
